//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class alumnes
{
    public alumnes()
    {
        this.avaluar = new HashSet<avaluar>();
        this.ufs = new HashSet<ufs>();
    }

    public int id { get; set; }
    public Nullable<System.DateTime> data_naixement { get; set; }
    public int id_curs { get; set; }

    public virtual cursos cursos { get; set; }
    public virtual persones persones { get; set; }
    public virtual ICollection<avaluar> avaluar { get; set; }
    public virtual ICollection<ufs> ufs { get; set; }
}

public partial class avaluacions
{
    public avaluacions()
    {
        this.avaluar = new HashSet<avaluar>();
    }

    public int id { get; set; }
    public string codi { get; set; }
    public string nom { get; set; }

    public virtual ICollection<avaluar> avaluar { get; set; }
}

public partial class avaluar
{
    public int id_alumne { get; set; }
    public int id_uf { get; set; }
    public int id_avaluacio { get; set; }
    public Nullable<double> nota { get; set; }

    public virtual alumnes alumnes { get; set; }
    public virtual avaluacions avaluacions { get; set; }
    public virtual ufs ufs { get; set; }
}

public partial class cicles
{
    public cicles()
    {
        this.cursos = new HashSet<cursos>();
    }

    public int id { get; set; }
    public string codi { get; set; }
    public string nom { get; set; }

    public virtual ICollection<cursos> cursos { get; set; }
}

public partial class cursos
{
    public cursos()
    {
        this.alumnes = new HashSet<alumnes>();
        this.moduls_prof = new HashSet<moduls_prof>();
    }

    public int id { get; set; }
    public string codi { get; set; }
    public string nom { get; set; }
    public int id_cicle { get; set; }
    public Nullable<int> id_tutor { get; set; }

    public virtual ICollection<alumnes> alumnes { get; set; }
    public virtual cicles cicles { get; set; }
    public virtual professors professors { get; set; }
    public virtual ICollection<moduls_prof> moduls_prof { get; set; }
}

public partial class moduls_prof
{
    public moduls_prof()
    {
        this.ufs = new HashSet<ufs>();
    }

    public int id_curs { get; set; }
    public int id { get; set; }
    public string codi { get; set; }
    public string nom { get; set; }
    public int hores { get; set; }
    public int hores_lliures { get; set; }
    public Nullable<int> id_professor { get; set; }

    public virtual cursos cursos { get; set; }
    public virtual professors professors { get; set; }
    public virtual ICollection<ufs> ufs { get; set; }
}

public partial class persones
{
    public int id { get; set; }
    public string dni { get; set; }
    public string nom { get; set; }
    public string cognom1 { get; set; }
    public string cognom2 { get; set; }
    public string telefon { get; set; }
    public string correu { get; set; }
    public string adreca { get; set; }
    public string tipus { get; set; }

    public virtual alumnes alumnes { get; set; }
    public virtual professors professors { get; set; }
}

public partial class professors
{
    public professors()
    {
        this.cursos = new HashSet<cursos>();
        this.moduls_prof = new HashSet<moduls_prof>();
    }

    public int id { get; set; }
    public string nom { get; set; }

    public virtual ICollection<cursos> cursos { get; set; }
    public virtual ICollection<moduls_prof> moduls_prof { get; set; }
    public virtual persones persones { get; set; }
}

public partial class ufs
{
    public ufs()
    {
        this.avaluar = new HashSet<avaluar>();
        this.alumnes = new HashSet<alumnes>();
    }

    public int id { get; set; }
    public string nom { get; set; }
    public int id_modul_prof { get; set; }

    public virtual ICollection<avaluar> avaluar { get; set; }
    public virtual moduls_prof moduls_prof { get; set; }
    public virtual ICollection<alumnes> alumnes { get; set; }
}
