//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class hoteles_basicoEntities : DbContext
{
    public hoteles_basicoEntities()
        : base("name=hoteles_basicoEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<cadenas> cadenas { get; set; }
    public DbSet<ciudades> ciudades { get; set; }
    public DbSet<hoteles> hoteles { get; set; }
    public DbSet<restaurantes> restaurantes { get; set; }
}
