//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class cadenas
{
    public cadenas()
    {
        this.hoteles = new HashSet<hoteles>();
    }

    public string cif { get; set; }
    public string nombre { get; set; }
    public string dir_fis { get; set; }

    public virtual ICollection<hoteles> hoteles { get; set; }
}

public partial class ciudades
{
    public ciudades()
    {
        this.hoteles = new HashSet<hoteles>();
    }

    public int id_ciudad { get; set; }
    public string nombre { get; set; }

    public virtual ICollection<hoteles> hoteles { get; set; }
}

public partial class hoteles
{
    public hoteles()
    {
        this.restaurantes = new HashSet<restaurantes>();
    }

    public int id_ciudad { get; set; }
    public string nombre { get; set; }
    public int categoria { get; set; }
    public string direccion { get; set; }
    public int telefono { get; set; }
    public string tipo { get; set; }
    public string cif { get; set; }

    public virtual cadenas cadenas { get; set; }
    public virtual ciudades ciudades { get; set; }
    public virtual ICollection<restaurantes> restaurantes { get; set; }
}

public partial class restaurantes
{
    public int id { get; set; }
    public string nombre { get; set; }
    public string especialidad { get; set; }
    public Nullable<int> id_ciudad { get; set; }
    public string nombre_hot { get; set; }

    public virtual hoteles hoteles { get; set; }
}
